services:
  alicia-ia:
    build: .
    container_name: alicia-ia-container
    restart: always

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    volumes:
      - .:/app
      - ./models:/app/models
      - ./cookies.txt:/app/cookies.txt
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis-server

  redis-server:
    image: redis:alpine
    container_name: alicia-redis
    restart: always
    ports:
      - "6379:6379"